import type { EmployeeBalance, EmployeeBalancesResponse } from '../../shared/types';

export const EMPLOYEE_BALANCE_STATUS_LABELS: Record<string, string> = {
  ALL: 'Все',
  NORMAL: 'Нормальный',
  LOW: 'Низкий баланс',
  NEGATIVE: 'Отрицательный баланс',
  HAS_PENDING: 'Есть заявки на согласовании',
};

export const BALANCE_TYPE_LABELS: Record<string, string> = {
  VACATION: 'Отпуск',
  TIME_OFF: 'Отгул',
  SICK_LEAVE: 'Больничный',
  UNPAID_LEAVE: 'Неоплачиваемый отпуск',
  BUSINESS_TRIP: 'Командировка',
  REMOTE_WORK: 'Удаленная работа',
};

function iso(day: number, month: number, year: number, hour: number, min: number): string {
  const d = String(day).padStart(2, '0');
  const m = String(month).padStart(2, '0');
  const h = String(hour).padStart(2, '0');
  const mi = String(min).padStart(2, '0');
  return `${year}-${m}-${d}T${h}:${mi}:00.000Z`;
}

export const EMPLOYEE_BALANCES_MOCK: EmployeeBalance[] = [
  {
    id: 'bal-1',
    employeeId: 'emp-1',
    employeeName: 'Иванов Иван',
    employeeInitials: 'ИИ',
    email: 'ivanov@company.ru',
    telegramUsername: '@ivanov_qa',
    department: 'QA',
    role: 'EMPLOYEE',
    balanceType: 'VACATION',
    initialHours: 0,
    accruedHours: 120,
    usedHours: 48,
    plannedHours: 0,
    pendingHours: 0,
    adjustmentHours: 0,
    availableHours: 72,
    projectedHours: 72,
    updatedAt: iso(15, 5, 2026, 10, 23),
  },
  {
    id: 'bal-2',
    employeeId: 'emp-2',
    employeeName: 'Петров Петр',
    employeeInitials: 'ПП',
    email: 'petrov@company.ru',
    telegramUsername: '@petrov_sap',
    department: 'SAP',
    role: 'EMPLOYEE',
    balanceType: 'VACATION',
    initialHours: 0,
    accruedHours: 120,
    usedHours: 60,
    plannedHours: 16,
    pendingHours: 8,
    adjustmentHours: 0,
    availableHours: 36,
    projectedHours: 28,
    updatedAt: iso(15, 5, 2026, 9, 58),
  },
  {
    id: 'bal-3',
    employeeId: 'emp-3',
    employeeName: 'Смирнова Анна',
    employeeInitials: 'СА',
    email: 'smirnova@company.ru',
    department: 'Dev',
    role: 'EMPLOYEE',
    balanceType: 'VACATION',
    initialHours: 0,
    accruedHours: 120,
    usedHours: 72,
    plannedHours: 32,
    pendingHours: 8,
    adjustmentHours: 0,
    availableHours: 8,
    projectedHours: 0,
    updatedAt: iso(14, 5, 2026, 16, 42),
  },
  {
    id: 'bal-4',
    employeeId: 'emp-4',
    employeeName: 'Кузнецов Алексей',
    employeeInitials: 'КА',
    email: 'kuznetsov@company.ru',
    telegramUsername: '@kuznetsov_dev',
    department: 'Dev',
    role: 'EMPLOYEE',
    balanceType: 'VACATION',
    initialHours: 0,
    accruedHours: 120,
    usedHours: 96,
    plannedHours: 16,
    pendingHours: 0,
    adjustmentHours: 0,
    availableHours: -4,
    projectedHours: -4,
    updatedAt: iso(15, 5, 2026, 11, 7),
  },
  {
    id: 'bal-5',
    employeeId: 'emp-5',
    employeeName: 'Соколова Мария',
    employeeInitials: 'СМ',
    email: 'sokolova@company.ru',
    department: 'HR',
    role: 'MANAGER',
    balanceType: 'TIME_OFF',
    initialHours: 0,
    accruedHours: 24,
    usedHours: 8,
    plannedHours: 8,
    pendingHours: 4,
    adjustmentHours: 0,
    availableHours: 4,
    projectedHours: 0,
    updatedAt: iso(15, 5, 2026, 8, 51),
  },
  {
    id: 'bal-6',
    employeeId: 'emp-6',
    employeeName: 'Орлова Екатерина',
    employeeInitials: 'ОЕ',
    email: 'orlova@company.ru',
    department: 'QA',
    role: 'EMPLOYEE',
    balanceType: 'VACATION',
    initialHours: 0,
    accruedHours: 120,
    usedHours: 56,
    plannedHours: 24,
    pendingHours: 8,
    adjustmentHours: 0,
    availableHours: 32,
    projectedHours: 24,
    updatedAt: iso(14, 5, 2026, 14, 33),
  },
  {
    id: 'bal-7',
    employeeId: 'emp-7',
    employeeName: 'Васильев Дмитрий',
    employeeInitials: 'ВД',
    email: 'vasilev@company.ru',
    telegramUsername: '@vasilev_sap',
    department: 'SAP',
    role: 'EMPLOYEE',
    balanceType: 'VACATION',
    initialHours: 0,
    accruedHours: 120,
    usedHours: 40,
    plannedHours: 16,
    pendingHours: 0,
    adjustmentHours: 0,
    availableHours: 64,
    projectedHours: 64,
    updatedAt: iso(15, 5, 2026, 9, 12),
  },
];

export function getMockBalancesResponse(
  items: EmployeeBalance[],
  page: number,
  limit: number,
): EmployeeBalancesResponse {
  const uniqueEmployees = new Set(items.map((i) => i.employeeId)).size;

  return {
    items,
    total: items.length,
    page,
    limit,
    summary: {
      totalEmployees: uniqueEmployees,
      totalAvailableHours: items.reduce((s, i) => s + i.availableHours, 0),
      totalPlannedHours: items.reduce((s, i) => s + i.plannedHours, 0),
      totalPendingHours: items.reduce((s, i) => s + i.pendingHours, 0),
      negativeBalanceCount: items.filter((i) => i.availableHours < 0).length,
    },
  };
}
