ALTER TYPE "RequestStatus" ADD VALUE 'ACTIVE';
ALTER TYPE "RequestStatus" ADD VALUE 'EXPIRED';

ALTER TYPE "LeaveRequestType" ADD VALUE 'OVERTIME';
ALTER TYPE "LeaveRequestType" ADD VALUE 'OVERWORK';
ALTER TYPE "LeaveRequestType" ADD VALUE 'REMOTE_WORK';
ALTER TYPE "LeaveRequestType" ADD VALUE 'OTHER';
